name: Deploy React to AWS Amplify (Prod)

on:
  push:
    branches:
      - main  # Deploy only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 

      - name: Deploy to Amplify
        run: |
          aws amplify start-job \
            --app-id d2h5sp7cp38qlv \
            --branch-name main \
            --job-type RELEASE
